apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pets
  name: pets
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30217
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pets
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 35.187.184.199
status:
  loadBalancer: {}
