apiVersion: v1
kind: Service
metadata:
  name: mongodb-shard1-arbiter-service
  labels:
    name: mongodb-shard1
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongodb-shard1
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongod-shard1-arbiter
spec:
  serviceName: mongodb-shard1-arbiter-service
  replicas: 1
  template:
    metadata:
      labels:
        role: mongodb-shard1
        tier: maindb
        replicaset: Shard1RepSet
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - Shard1RepSet
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongod-shard1-container
          image: mongo
          command:
            - "numactl"
            - "--interleave=all"
            - "mongod"
            - "--port"
            - "27017"
            - "--wiredTigerCacheSizeGB"
            - "0.25"
            - "--bind_ip"
            - "0.0.0.0"
            - "--shardsvr"
              #            - "--replSet"
              #            - "Shard1RepSet"
          resources:
            requests:
              cpu: 0.25
              memory: 512Mi
          ports:
            - containerPort: 27017
  volumeClaimTemplates:
  - metadata:
      name: mongo-shard1-persistent-storage-claim
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 8Gi
