apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: grafana
  namespace: monitoring
spec:
  maxReplicas: 100
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prometheus-operator-grafana
  targetCPUUtilizationPercentage: 60
