apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pets
  namespace: default
spec:
  maxReplicas: 100
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pets
  targetCPUUtilizationPercentage: 60
