{
 "title": "MongoDB",
 "description": "MongoDB Prometheus Exporter Dashboard. \r\nWorks well with https://github.com/dcu/mongodb_exporter\r\n\r\nIf you have the node_exporter running on the mongo instance, you will also get some useful alert panels related to disk io and cpu.",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": "label_values(mongodb_mongos_connections, instance)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "cluster", "label": "Cluster", "query": "label_values(cluster)" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Shards",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_shards_total{cluster=\"$cluster\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_chunks_total{cluster=\"$cluster\"})",
     "legendFormat": "Chunks"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_mongos_connections{instance=~\"$env\",state=\"current\"}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_mongos_connections{instance=~\"$env\",state=\"available\"}"
    }
   ]
  },
  {
   "title": "Sharded Collections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_collections_total{cluster=\"$cluster\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Sharded DBs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_databases_total{cluster=\"$cluster\", type=\"partitioned\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Chunks Balanced",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(mongodb_mongos_sharding_chunks_is_balanced{cluster=\"$cluster\"})",
     "legendFormat": "Cluster Balanced"
    }
   ]
  },
  {
   "title": "Balancer Enabled",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_balancer_enabled{cluster=\"$cluster\"})",
     "legendFormat": "Cluster Balanced"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_mongos_instance_uptime_seconds{instance=~\"$env\"}"
    }
   ]
  },
  {
   "title": "Unsharded DBs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_databases_total{cluster=\"$cluster\", type=\"unpartitioned\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  { "title": "Mongos Query Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "env" },
  {
   "title": "Queries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongos_op_counters_total{instance=~\"$env\", type=\"query\"}[$interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Inserts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongos_op_counters_total{instance=~\"$env\", type=\"insert\"}[$interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Updates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongos_op_counters_total{instance=~\"$env\", type=\"update\"}[$interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Deletes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongos_op_counters_total{instance=~\"$env\", type=\"delete\"}[$interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Query Summary",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongos_op_counters_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Mongos Operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongos_op_counters_total{cluster=\"$cluster\", type!=\"command\"}[$interval]) or irate(mongodb_mongos_op_counters_total{cluster=\"$cluster\", type!=\"command\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Shard Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Connections Per Shard",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mongodb_mongod_connections{cluster=\"$cluster\", state=\"current\"} * on (instance) group_right mongodb_mongod_replset_my_state{cluster=\"$cluster\"}/ mongodb_mongod_replset_my_state{cluster=\"$cluster\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Operations Per Shard",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(sum(rate(mongodb_mongod_op_counters_total{cluster=\"$cluster\", type!=\"command\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{cluster=\"$cluster\", type!=\"command\"}[5m])) by (instance) * on (instance) group_right mongodb_mongod_replset_my_state{cluster=\"$cluster\"} / mongodb_mongod_replset_my_state{cluster=\"$cluster\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Shard Elections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(changes(mongodb_mongod_replset_member_election_date{cluster=\"$cluster\"}[$interval])) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Chunks by Shard",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max_over_time(mongodb_mongos_sharding_shard_chunks_total{cluster=\"$cluster\"}[$interval]) or \nmax_over_time(mongodb_mongos_sharding_shard_chunks_total{cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Replication Lag by Set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(mongodb_mongod_replset_member_optime_date{cluster=\"$cluster\", state=\"PRIMARY\"}) by (set) - min(mongodb_mongod_replset_member_optime_date{cluster=\"$cluster\", state=\"SECONDARY\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongos_memory{instance=~\"$env\",type=~\"resident|virtual\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongos_network_bytes_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(rate(node_disk_io_time_seconds_total[5m])/1000 or irate(node_disk_io_time_seconds_total[5m])/1000)",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Reads Completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total[5m])",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Writes Completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total[5m])",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  }
 ]
}